name: Rust
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install node dependencies
        run: npm install
      - name: Build templates
        run: npm run build
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
